//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfonichevKinderGarden.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public Mark()
        {
            this.Journal = new HashSet<Journal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Journal> Journal { get; set; }
    }
}
