//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfonichevKinderGarden.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinderGardenEntities : DbContext
    {
        public KinderGardenEntities()
            : base("name=KinderGardenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activity { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<GroupDS> GroupDS { get; set; }
        public DbSet<Journal> Journal { get; set; }
        public DbSet<Mark> Mark { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<VidGroup> VidGroup { get; set; }
    }
}
